### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by pabb85** [TeamWalrus/Walrus#106]
Hi there, 

I'd like to get involved in the development of this project if I may?

Thank you, 
Paul

**Comment by dunderhay** [comment]
@pabb85 what is your email address? Will invite you to the slack channel

**Comment by dunderhay** [comment]
@pabb85 here is a link to join the slack channel
https://join.slack.com/t/walrusapp/shared_invite/enQtNDI0NDc1MDMzNDk0LTk5MTdhNWE4ZjBkNDBkOTkzY2EzMWE0ZWU3MDEwZjYzZmViZDFlZDQ5NDU1ZmZkZTdkMWVjMDVjYzkxZDFjODA

**Comment by pabb85** [comment]
Thank you :)
