### ISSUE TITLE
Walrus not working with iceman1001 firmware

### ISSUE THREAD

**Issue by riskynacho** [TeamWalrus/Walrus#108]
I tried the iceman 1001 firmware (latest) on my proxmark3 rdv2 and walrus isn't able to detect a card scan. It does detect a proxmark3 has been connected, when I goto read card, it never detects the card. 

Is this a known condition?

**Comment by original13** [comment]
He mentioned that there is a fix required in this other issue thread...

https://github.com/TeamWalrus/Walrus/issues/102

**Comment by megabug** [comment]
This should be fixed by iceman1001/proxmark3@03239550 and iceman1001/proxmark3@821f12d4.
