### ISSUE TITLE
Incorrect HID format detection

### ISSUE THREAD

**Issue by Defensor7** [TeamWalrus/Walrus#109]
There is problem with HID card format detection and decoding.

Proxmark output:
HID Prox TAG ID: 2004356945 (46242) - Format Len: 26bit - FC: 26 - Card: 46242

Walrus output:
FC 67, CN 177314 (HID 37-bit with Facility Code (H10304))

**Comment by megabug** [comment]
Thanks! There was indeed a problem where it would incorrectly decode cards as being 37-bit. This has been fixed in 4bc72a3.
